## Server Properties
server.port=${PORT:5000}
server.compression.enabled=true

## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:polling_app}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

## Hibernate Properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

## Database Initialization
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

## Hibernate Logging
logging.level.org.hibernate.SQL=WARN

## Jackson Properties
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
spring.jackson.time-zone=UTC

## App Properties
app.jwtSecret=${JWT_SECRET:JWTSuperSecretKey}
app.jwtExpirationInMs=604800000
